---
driver:
  name: vagrant
  network:
    - ["private_network", {ip: "192.168.33.33"}]

provisioner:
  name: chef_zero

platforms:
  - name: centos-7.2
    driver:
      customize:
        memory: 256

suites:
  - name: default
    data_bags_path: "../../data_bags"
    run_list:
      - recipe[awesome_customers_rhel::default]
    provisioner:
      encrypted_data_bag_secret_key_path: "../../.chef/encrypted_data_bag_secret"
    attributes:
      awesome_customers_rhel:
        secret_file: '/tmp/kitchen/encrypted_data_bag_secret'
