---
driver:
  name: vagrant
  network:
    - ["private_network", {ip: "192.168.33.33"}]

provisioner:
  name: chef_zero

platforms:
  - name: centos-7.2
    driver:
      customize:
        memory: 256

suites:
  - name: default
    run_list:
      - recipe[awesome_customers_rhel::default]
    attributes:
      awesome_customers_rhel:
        database:
          root_password: 'mysql_root_password'
          admin_password: 'mysql_admin_password'
